FROM --platform=linux/amd64 node:18.8.0
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
WORKDIR /usr/src/app
RUN yarn global add serverless 
# リバースプロキシ用のNginx
RUN apt -y update && apt -y install nginx
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]