version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    volumes:
      - ./:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    tty: true
    stdin_open: true 
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_OUTPUT=json